const SUPABASE_URL = "https://selnuwzcdzkjmbjthxwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_4vd7mYjgt1hkmEsivXpk9g_Z5IndKqL";
const { createClient } = supabase;
const db = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
function toast(s){const t=document.getElementById('toast');if(!t)return;t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
function status(ok,s){const e=document.getElementById('dbStatus');e.textContent='● '+s;e.classList.toggle('online',ok)}
async function login(){const email=document.getElementById('email').value.trim(),password=document.getElementById('password').value;if(!email||!password)return toast('Email et mot de passe requis.');const {error}=await db.auth.signInWithPassword({email,password});if(error)return toast('Connexion refusée.');await checkAuth()}
async function logout(){await db.auth.signOut();await checkAuth()}
async function checkAuth(){const {data:{session}}=await db.auth.getSession();if(!session){document.getElementById('loginBox').style.display='grid';document.getElementById('panel').style.display='none';status(true,'SUPABASE CONNECTÉ');return}document.getElementById('loginBox').style.display='none';document.getElementById('panel').style.display='block';status(true,'RESPONSABLE CONNECTÉ');await Promise.all([loadStats(),loadRegistrations()])}
async function loadStats(){const e=await db.from('events').select('id',{count:'exact',head:true});document.getElementById('statEvents').textContent=e.count||0;const r=await db.from('registrations').select('id',{count:'exact',head:true});document.getElementById('statPlayers').textContent=r.count||0;const m=await db.from('matches').select('player_name');document.getElementById('statRanking').textContent=(m.data||[]).length}
async function loadRegistrations(){const {data,error}=await db.from('registrations').select('id,event_id,name,discord,equipment,status,created_at').order('created_at',{ascending:false}).limit(20);const el=document.getElementById('registrationList');if(error||!data?.length){el.textContent='Aucune inscription récente.';return}el.innerHTML=data.map(x=>`<div style="padding:10px 0;border-bottom:1px solid #273028"><strong>${x.name}</strong> — ${x.equipment||'Matériel personnel'}<br><small>${x.discord||''} • ${x.status||''}</small></div>`).join('')}
async function addEvent(){const title=document.getElementById('eventTitle').value.trim();if(!title)return toast('Nom de l’événement requis.');const {error}=await db.from('events').insert({title,event_date:document.getElementById('eventDate').value||null,start_time:document.getElementById('eventTime').value||null,description:document.getElementById('eventDesc').value||null,location:document.getElementById('eventLocation').value||null,max_places:Number(document.getElementById('eventPlaces').value)||null,status:'open'});if(error)return toast('Publication refusée : vérifie les droits Supabase.');toast('Événement publié.');await loadStats()}
async function addPlayer(){const name=document.getElementById('playerName').value.trim();if(!name)return toast('Nom du joueur requis.');const {error}=await db.from('matches').insert({player_name:name,matches_played:Number(document.getElementById('playerMatches').value)||0,wins:Number(document.getElementById('playerWins').value)||0,losses:Number(document.getElementById('playerLosses').value)||0,points:Number(document.getElementById('playerPoints').value)||0});if(error)return toast('Ajout refusé : vérifie les droits Supabase.');toast('Joueur ajouté.');await loadStats()}
async function resetRanking(){if(!confirm('Vider définitivement le classement actuel ?'))return;const {error}=await db.from('matches').delete().neq('player_name','__never__');if(error)return toast('RAZ refusée : ajoute la policy DELETE admin.');toast('Classement remis à zéro.');await loadStats()}
checkAuth();
