const defaultEvents=[{name:'SESSION SPEEDSOFT',time:'20:30',desc:'5v5 • manches courtes • élimination'},{name:'OPÉRATION CQB',time:'21:30',desc:'Attaque / défense • objectif central'},{name:'GREEN SHIELD',time:'20:00',desc:'Protection VIP • escorte • extraction'}];
const defaultPlayers=[{name:'R. McCall',m:8,w:6,d:2},{name:'C. McCall',m:7,w:5,d:2},{name:'A. Reed',m:6,w:4,d:2},{name:'D. Wolf',m:5,w:3,d:2}];
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))||d}catch(e){return d}};const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function render(){let ev=get('saac_events',defaultEvents),pl=get('saac_players',defaultPlayers);
document.getElementById('eventList').innerHTML=ev.map(e=>`<div class="event"><time>${e.time}</time><div><small>SAAC EVENT</small><h3>${e.name}</h3><p>${e.desc}</p></div><button onclick="registerEvent('${e.name.replaceAll("'","\\'")}')">S'INSCRIRE</button></div>`).join('');
document.getElementById('rankingList').innerHTML=pl.sort((a,b)=>b.w-a.w).map((p,i)=>`<div class="tr"><span>${i+1}</span><strong>${p.name}</strong><span>${p.m}</span><span>${p.w}</span><span>${p.d}</span><strong>${p.w*3}</strong></div>`).join('');
statEvents.textContent=ev.length;statPlayers.textContent=ev.length;statRanking.textContent=pl.length}
function addEvent(){let n=eventName.value.trim(),t=eventTime.value.trim(),d=eventDesc.value.trim();if(!n||!t){toast('Nom et horaire requis');return}let a=get('saac_events',defaultEvents);a.push({name:n,time:t,desc:d||'Événement SAAC'});save('saac_events',a);eventName.value=eventTime.value=eventDesc.value='';render();toast('Événement publié')}
function addPlayer(){let n=playerName.value.trim();if(!n){toast('Nom du joueur requis');return}let a=get('saac_players',defaultPlayers);a.push({name:n,m:+playerMatches.value||0,w:+playerWins.value||0,d:+playerLosses.value||0});save('saac_players',a);playerName.value=playerMatches.value=playerWins.value=playerLosses.value='';render();toast('Joueur ajouté')}
function registerEvent(n){toast('Inscription demandée : '+n)}function toast(s){let t=document.getElementById('toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}render();